# Generated by Django 5.1.1 on 2024-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='choices',
            field=models.CharField(blank=True, choices=[('dancing', 'Dancing'), ('music', 'Music')], max_length=100, null=True),
        ),
    ]
