# Generated by Django 5.1.1 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_remove_user_choices_delete_hobby_user_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dancing', 'Dancing'), ('music', 'Music')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='choices',
        ),
        migrations.AddField(
            model_name='user',
            name='choices',
            field=models.ManyToManyField(blank=True, to='new.hobby'),
        ),
    ]
