# Generated by Django 5.1.1 on 2024-09-20 05:26

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_alter_hobby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
